services:

  db:
    image: postgres:16-alpine
    container_name: cleclat_db          # Nouveau nom unique pour éviter conflit
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mot_de_passe
      POSTGRES_DB: cleclat              # Nom de la base cleclat
    ports:
      - "5433:5432"                     # Port local modifié pour éviter conflit
    volumes:
      - cleclat_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cleclat_backend     # Nouveau nom backend pour cohérence
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://myuser:mot_de_passe@db:5432/cleclat
    ports:
      - "5010:5000"                     # Port local modifié pour éviter conflit
    volumes:
      - ./backend:/app:ro
      - ./backend/migrations:/app/migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cleclat_frontend   # Nouveau nom frontend cohérent
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3001:80"                      # Port modifié pour éviter conflit avec ancien frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  cleclat_postgres_data:
