services:
  db_esme:
    image: postgres:13
    container_name: cleclat_db   # <- nouveau nom unique ici
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mot_de_passe
      POSTGRES_DB: cleclat
    ports:
      - "5433:5432"   # Change aussi le port local si tu veux éviter conflit avec l'ancien
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask_app_esme:
    build: .
    container_name: flask_app_cleclat  # Aussi ici pour garder cohérence et éviter conflit
    depends_on:
      - db_esme
    environment:
      - DATABASE_URL=postgresql://myuser:mot_de_passe@cleclat_db:5432/cleclat
    ports:
      - "5010:5000"  # Change aussi le port local si besoin
    volumes:
      - .:/app
      - ./migrations:/app/migrations

volumes:
  postgres_data:
